---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggcrqr

<!-- badges: start -->
<!-- badges: end -->

The goal of ggcrqr is to provide `R` routines for estimation of Generalized Gompertz Cure Rate Quantile Regression models.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("brsantos/ggcrqr")
```
## Example

This is a basic example which shows you how to estimate the model considering the data available in the package: `m_breast_cancer`.

```{r example, warning = FALSE}
library(ggcrqr)
## basic example code
## one should check whether the values for burn and jump are adequate.
model <- bayesGG(time_to_d ~ age_group + stage_c, 
                 ~ 1, 
                 ~ 1,
                 data = m_breast_cancer, 
                 q = 0.5, d = "cens", burn = 30000, jump = 40, 
                 guess = c(-0.1, 0.5, rep(0, 6)))
```

